2022-10-07 12:27:54,893, INFO, Bot running.., root
2022-10-07 12:28:03,224, INFO, Получен ответ: {'coord': {'lon': 80.2644, 'lat': 41.1231}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'пасмурно', 'icon': '04d'}], 'base': 'stations', 'main': {'temp': 18.81, 'feels_like': 17.37, 'temp_min': 18.81, 'temp_max': 18.81, 'pressure': 1020, 'humidity': 24, 'sea_level': 1020, 'grnd_level': 899}, 'visibility': 10000, 'wind': {'speed': 2.39, 'deg': 221, 'gust': 3}, 'clouds': {'all': 100}, 'dt': 1665123840, 'sys': {'country': 'CN', 'sunrise': 1665103273, 'sunset': 1665144737}, 'timezone': 28800, 'id': 1529660, 'name': 'Аксу', 'cod': 200}, root
2022-10-07 12:28:07,764, ERROR, Сайт не доступен, код ответа 404, root
2022-10-07 12:28:07,956, ERROR, Произошла ошибка: 'int' object is not subscriptable, root
2022-10-07 12:28:09,116, ERROR, Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message text is empty, TeleBot
2022-10-07 12:28:09,126, ERROR, Exception traceback:
Traceback (most recent call last):
  File "C:\myprojects\botpy\venv\lib\site-packages\telebot\__init__.py", line 977, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\myprojects\botpy\venv\lib\site-packages\telebot\util.py", line 154, in raise_exceptions
    raise self.exception_info
  File "C:\myprojects\botpy\venv\lib\site-packages\telebot\util.py", line 98, in run
    task(*args, **kwargs)
  File "c:\myprojects\botpy\main.py", line 118, in send_message
    bot.send_message(message.chat.id, weather)
  File "C:\myprojects\botpy\venv\lib\site-packages\telebot\__init__.py", line 1451, in send_message
    apihelper.send_message(
  File "C:\myprojects\botpy\venv\lib\site-packages\telebot\apihelper.py", line 267, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "C:\myprojects\botpy\venv\lib\site-packages\telebot\apihelper.py", line 152, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\myprojects\botpy\venv\lib\site-packages\telebot\apihelper.py", line 179, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message text is empty
, TeleBot
2022-10-07 12:28:10,303, ERROR, Сайт не доступен, код ответа 404, root
2022-10-07 12:28:10,781, ERROR, Произошла ошибка: 'int' object is not subscriptable, root
2022-10-07 12:28:11,410, ERROR, Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message text is empty, TeleBot
2022-10-07 12:28:11,419, ERROR, Exception traceback:
Traceback (most recent call last):
  File "C:\myprojects\botpy\venv\lib\site-packages\telebot\__init__.py", line 977, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\myprojects\botpy\venv\lib\site-packages\telebot\util.py", line 154, in raise_exceptions
    raise self.exception_info
  File "C:\myprojects\botpy\venv\lib\site-packages\telebot\util.py", line 98, in run
    task(*args, **kwargs)
  File "c:\myprojects\botpy\main.py", line 118, in send_message
    bot.send_message(message.chat.id, weather)
  File "C:\myprojects\botpy\venv\lib\site-packages\telebot\__init__.py", line 1451, in send_message
    apihelper.send_message(
  File "C:\myprojects\botpy\venv\lib\site-packages\telebot\apihelper.py", line 267, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "C:\myprojects\botpy\venv\lib\site-packages\telebot\apihelper.py", line 152, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\myprojects\botpy\venv\lib\site-packages\telebot\apihelper.py", line 179, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message text is empty
, TeleBot
